import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:ziarul_argesul/pages/category_page.dart';
import 'package:ziarul_argesul/pages/terms_and_conditions_page.dart';
import 'package:ziarul_argesul/util/transitions.dart';

import '../ads/ad_helper.dart';

/// Class responsible for the visual configuration of the side drawer, but also
/// for the implementation of the actions generated by the buttons contained in it.
class NavigationDrawerWidget extends StatelessWidget {
  final padding = const EdgeInsets.symmetric(horizontal: 20);
  /// Listing all of the news categories. List isn't dynamic so any modification
  /// made here should be reflected in the existing ListTiles.
  static const List<String> categories = [
    "Stiri Arges",
    "Stiri Pitesti",
    "Administrativ",
    "Editorial",
    "Sport",
    "Anunturi",
    "Termeni si Conditii"];
  NavigationDrawerWidget({super.key});
  final Uri toLaunch = Uri(scheme: 'https', host: 'www.ziarulargesul.ro');
  @override
  Widget build(BuildContext context) =>  Drawer(
      child: ListView (
      padding: EdgeInsets.zero,
        children:  [
          /// Visually configure the drawer header.
          const DrawerHeader(
            margin: EdgeInsets.symmetric(vertical:0, horizontal: 20),
            decoration: BoxDecoration(
              border: Border(
                top: BorderSide.none,
                bottom: BorderSide(color: Colors.transparent, width: 0.0),
                left: BorderSide(width: 5.0, color: Colors.transparent),
                right: BorderSide(width: 5.0, color: Colors.transparent),
              ),
              image: DecorationImage(
                image: AssetImage("images/argesul_drawer.png"),
                alignment: Alignment(0.7,0.7),
                fit: BoxFit.fitWidth,
              ),
            ),
            child: Text(
                '', style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 40,
            ),),
          ),
          ListTile(
            title:  Text(categories[0]),
            leading: const Icon(Icons.map_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[0]))
              );
            },
          ),
          ListTile(
            title: Text(categories[1]),
            leading: const Icon(Icons.location_city_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[1]))
              );
            },
          ),
          ListTile(
            title: Text(categories[2]),
            leading: const Icon(Icons.account_balance_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[2]))
              );
            },
          ),
          ListTile(
            title: Text(categories[3]),
            leading: const Icon(Icons.article_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[3]))
              );
            },
          ),
          ListTile(
            title: Text(categories[4]),
            leading: const Icon(Icons.sports_soccer_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[4]))
              );
            },
          ),
          ListTile(
            title: Text(categories[5]),
            leading: const Icon(Icons.ads_click_sharp),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: Category(categories[5]))
              );
            },
          ),
          ListTile(
            title: Text(categories[6]),
            leading: const Icon(Icons.info_outline_rounded),
            onTap: () {
              loadAndShowCategoryPageInterstitialAd();
              Navigator.push(
                  context, SlideLeftRoute(page: TermsAndConditionsPage())
              );
            },
          ),
        ],
      )
  );

  void loadAndShowCategoryPageInterstitialAd() {
    InterstitialAd.load(
        adUnitId: AdHelper.articleInterstitialAdUnitId,
        request: const AdRequest(),
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (ad) {
            debugPrint('Timeline page: Interstitial ad loaded');
            ad.show();
          },
          onAdFailedToLoad: (LoadAdError error) {
            debugPrint('Timeline page: Interstitial ad failed to load: $error');
          },
        )
    );
  }
}